name: CI

on: push

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci

      - name: check prettier
        run: npm run lint

  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci

      - name: Build web bundle
        run: npm run build

      - name: Upload build artifacts
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build

  test:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm ci

      - name: Jest tests
        run: npm run test

      - name: Generate coverage badge
        run: npx make-coverage-badge --output-path ./coverage/badge.svg

      - name: Upload coverage artifacts
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage

  deploy:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs:
      - build
      - test
    runs-on: ubuntu-20.04

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts
          path: public
      - name: Download coverage artifacts
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
          path: public/coverage

      - name: Publish site and coverage report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
